template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW:
  
  This patch adresses changes in PoE2 patch 0.1.1 and also adds a bit of finetuning here and there.
  Changed "Overseer's Precursor Tablet" to "Overseer Precursor Tablet"
  
  ## CHANGES:
  
  - Changed
  - Economy adjusted the tiering of some catalsts, currency, fragments etc
  - Added the new "Overseer's Precursor Tablet"
  - Reworked flasks and crafting sections slightlx to adjust for the new glassblower salvaging change
  - Slightly retiered rare/crafting bases
  - Slightly adjusted the tiering on some salvaging rules
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
